{{ if .Values.deployWatchman }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-watchman
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/moov-io/charts
    targetRevision: HEAD
    path: stable/watchman
    helm:
      values: |       
        namespace: moov        
  destination:
    server: https://kubernetes.default.svc
    namespace: moov
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
{{ end }}